language: ruby
cache: bundler

env:
- MOZ_HEADLESS=1
addons:
  firefox: latest

rvm:
- "2.5.1"

before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver

before_script: 'bundle install'

script: 'bundle exec cucumber'
